name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    name: Python (black/ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install formatters
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0 ruff==0.6.4
      - name: Black check
        run: black --check backend
      - name: Ruff check
        run: ruff check backend

  web:
    name: Web (prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Prettier check
        run: npx --yes prettier@3.3.3 --check "web/**/*.{js,jsx,ts,tsx,css,html,json,md}"
# (opcjonalnie w przyszłości: dodać build web i krótkie testy API)
